sudo: false
cache:
  directories:
  - $HOME/.stack/

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - chmod a+x ~/.local/bin/stack
  - chmod a+x ./travis_long

install:
  - ./travis_long stack --no-terminal setup
  - ./travis_long stack --no-terminal test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test