flags: {}
packages:
- '.'
- location:
    git: git@github.com:Teaspot-Studio/arhelk-core.git
    commit: 70d9e06ad968bce1d6a7c72695905cf856ec1ad7
- location:
    git: git@github.com:Teaspot-Studio/arhelk-lexer.git
    commit: 385b0d8d49f843381bacfc73e648db24cf2045e8
extra-deps: []
resolver: lts-3.12
